package processor

import (
	"testing"

	"github.com/louiss0/mace/internal/lexer"
	"github.com/louiss0/mace/internal/parser/ast"
)

func TestCoverageMatrixBranches(t *testing.T) {
	vars := newVariableRegistry()
	symbols := newSymbolTable()
	types := newTypeRegistry()
	schemas := newSchemaRegistry()
	schema := ast.RecordType{Fields: []ast.SchemaField{{Name: "name", Type: ast.PrimitiveType{Name: "string"}}, {Name: "opt", Optional: true, Type: ast.PrimitiveType{Name: "string"}}}}
	schemas.Add("User", schema)
	symbols.Add("User", symbolKindSchema)
	symbols.Add("Thing", symbolKindType)
	symbols.Add("Imported", symbolKindImport)
	types.AddAlias("Alias", ast.NamedType{Name: "User"})
	types.AddAlias("CycleA", ast.NamedType{Name: "CycleB"})
	types.AddAlias("CycleB", ast.NamedType{Name: "CycleA"})
	vars.Add("record", valueType{kind: ValueRecord, schemaName: "User", record: &schema})
	vars.Add("array", valueType{kind: ValueArray, element: &valueType{kind: ValueString}})
	vars.Add("choice", valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}, {Kind: ValueString, String: "Bea"}}})
	vars.Add("variant", valueType{members: []valueType{{kind: ValueString}, {kind: ValueInt}}})

	_, _ = schemaTypeFromTypeReference(ast.PrimitiveType{Name: "string"}, types)
	_, _ = schemaTypeFromTypeReference(ast.NamedType{Name: "User"}, types)
	_, _ = schemaTypeFromTypeReference(ast.ArrayType{Element: ast.PrimitiveType{Name: "string"}}, types)
	_, _ = schemaTypeFromTypeReference(ast.RecordMapType{Value: ast.PrimitiveType{Name: "string"}}, types)
	_, _ = schemaTypeFromTypeReference(ast.UnionType{Members: []ast.TypeReference{ast.NamedType{Name: "User"}}}, types)
	_, _ = schemaTypeFromTypeReference(ast.VariantType{Members: []ast.TypeReference{ast.PrimitiveType{Name: "string"}, ast.PrimitiveType{Name: "int"}}}, types)
	_, _ = schemaTypeFromTypeReference(ast.ChoiceType{Members: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, types)
	_, _ = schemaTypeFromTypeReference(ast.RecordType{Fields: []ast.SchemaField{{Name: "name", Type: ast.PrimitiveType{Name: "string"}}}}, types)
	_, _ = schemaTypeFromTypeReference(nil, types)

	_, _ = resolveExportedTypeReference(ast.PrimitiveType{Name: "string"}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.ArrayType{Element: ast.NamedType{Name: "User"}}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.RecordMapType{Value: ast.NamedType{Name: "User"}}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.UnionType{Members: []ast.TypeReference{ast.NamedType{Name: "User"}}}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.VariantType{Members: []ast.TypeReference{ast.PrimitiveType{Name: "string"}, ast.PrimitiveType{Name: "int"}}}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.ChoiceType{Members: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.RecordType{Fields: []ast.SchemaField{{Name: "name", Type: ast.NamedType{Name: "User"}}}}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.NamedType{Name: "User"}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.NamedType{Name: "Alias"}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.NamedType{Name: "CycleA"}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(ast.NamedType{Name: "Missing"}, types, schemas, map[string]struct{}{}, map[string]struct{}{})
	_, _ = resolveExportedTypeReference(nil, types, schemas, map[string]struct{}{}, map[string]struct{}{})

	_, _ = resolveValueType(ast.PrimitiveType{Name: "string"}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.ArrayType{Element: ast.PrimitiveType{Name: "string"}}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.RecordMapType{Value: ast.PrimitiveType{Name: "string"}}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.ChoiceType{Members: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.UnionType{Members: []ast.TypeReference{ast.NamedType{Name: "User"}}}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.VariantType{Members: []ast.TypeReference{ast.PrimitiveType{Name: "string"}, ast.PrimitiveType{Name: "int"}}}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.RecordType{Fields: []ast.SchemaField{{Name: "name", Type: ast.PrimitiveType{Name: "string"}}}}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.NamedType{Name: "User"}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.NamedType{Name: "Alias"}, symbols, types, schemas, nil)
	_, _ = resolveValueType(ast.NamedType{Name: "Missing"}, symbols, types, schemas, nil)
	_, _ = resolveValueType(nil, symbols, types, schemas, nil)

	_ = validateTypeReference(ast.ArrayType{Element: ast.PrimitiveType{Name: "string"}}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.RecordMapType{Value: ast.PrimitiveType{Name: "string"}}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.UnionType{Members: []ast.TypeReference{ast.NamedType{Name: "User"}}}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.VariantType{Members: []ast.TypeReference{ast.PrimitiveType{Name: "string"}, ast.PrimitiveType{Name: "int"}}}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.RecordType{Fields: []ast.SchemaField{{Name: "name", Type: ast.PrimitiveType{Name: "string"}}}}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.ChoiceType{Members: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.NamedType{Name: "User"}, symbols, types, schemas, nil)
	_ = validateTypeReference(ast.NamedType{Name: "Missing"}, symbols, types, schemas, nil)
	_ = validateTypeReference(nil, symbols, types, schemas, nil)

	_ = validateExpressionAgainstType(ast.StringLiteral{Lexeme: `"Ada"`}, valueType{kind: ValueString}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.ArrayLiteral{Elements: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, valueType{kind: ValueArray, element: &valueType{kind: ValueString}}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.RecordLiteral{Fields: []ast.RecordField{{Name: "name", Value: ast.StringLiteral{Lexeme: `"Ada"`}}}}, valueType{kind: ValueRecord, record: &schema}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bea"`}}, valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}, {Kind: ValueString, String: "Bea"}}}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.Identifier{Name: "choice"}, valueType{members: []valueType{{kind: ValueString}, {kind: ValueInt}}}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.IntLiteral{Lexeme: "1"}}, valueType{kind: ValueString}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.BooleanLiteral{Value: true}, valueType{kind: ValueUnknown}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.BooleanLiteral{Value: true}, valueType{kind: ValueString, nullable: true}, vars, symbols, types, schemas, nil)
	_ = validateExpressionAgainstType(ast.ArrayAccess{Target: ast.StringLiteral{Lexeme: `"Ada"`}, Index: ast.IntLiteral{Lexeme: "0"}}, valueType{kind: ValueString}, vars, symbols, types, schemas, nil)

	_ = validateEvaluatedValueAgainstType(Value{Kind: ValueNull}, valueType{kind: ValueString, nullable: true}, symbols, types, schemas, nil)
	_ = validateEvaluatedValueAgainstType(Value{Kind: ValueString, String: "Ada"}, valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}}}, symbols, types, schemas, nil)
	_ = validateEvaluatedValueAgainstType(Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}}, valueType{kind: ValueRecord, schemaName: "User", record: &schema}, symbols, types, schemas, nil)
	_ = validateEvaluatedValueAgainstType(Value{Kind: ValueArray, Array: []Value{{Kind: ValueString, String: "Ada"}}}, valueType{kind: ValueArray, element: &valueType{kind: ValueString}}, symbols, types, schemas, nil)
	_ = validateEvaluatedValueAgainstType(Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}, "extra": {Kind: ValueString, String: "Ada"}}}, valueType{kind: ValueRecord, schemaName: "User"}, symbols, types, schemas, nil)
	_ = validateEvaluatedValueAgainstType(Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}}, valueType{members: []valueType{{kind: ValueRecord, schemaName: "User"}, {kind: ValueRecord, schemaName: "User"}}}, symbols, types, schemas, nil)
	_ = validateEvaluatedValueAgainstVariantMembers(Value{Kind: ValueString, String: "Ada"}, []valueType{{kind: ValueInt}, {kind: ValueInt}}, symbols, types, schemas, nil)

	_, _ = evaluateSchemaOutput(ast.OutputBlock{Mode: ast.OutputModeSchema, SchemaFields: []ast.OutputSchemaField{{Name: "name", Type: ast.PrimitiveType{Name: "string"}}}}, types)
	_, _ = evaluateSchemaOutput(ast.OutputBlock{Mode: ast.OutputModeData}, types)
	_, _ = coerceEvaluatedValueAgainstType(ast.StringLiteral{Lexeme: `"Ada"`}, Value{Kind: ValueString, String: "Ada"}, valueType{kind: ValueString}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = coerceEvaluatedValueAgainstType(ast.ArrayLiteral{Elements: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, Value{Kind: ValueArray, Array: []Value{{Kind: ValueString, String: "Ada"}}}, valueType{kind: ValueArray, element: &valueType{kind: ValueString}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)

	_, _ = evaluateExpression(ast.Identifier{Name: "record"}, contextValues("record", Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}}), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.MemberAccess{Target: ast.Identifier{Name: "record"}, Name: "name"}, contextValues("record", Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}}), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.ArrayAccess{Target: ast.ArrayLiteral{Elements: []ast.Expression{ast.IntLiteral{Lexeme: "1"}}}, Index: ast.IntLiteral{Lexeme: "0"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.PrefixExpression{Operator: lexer.TokenMinus, Right: ast.IntLiteral{Lexeme: "1"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.InfixExpression{Operator: lexer.TokenPlus, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "2"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bea"`}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.RecordLiteral{Fields: []ast.RecordField{{Name: "name", Value: ast.StringLiteral{Lexeme: `"Ada"`}}}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateExpression(ast.SelfReference{Path: []string{"name"}}, newValueEnvironment(), Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}}, symbols, types, schemas, nil)
	var badExpr ast.Expression
	_, _ = evaluateExpression(badExpr, newValueEnvironment(), Value{}, symbols, types, schemas, nil)

	_, _ = parseHexFloat("0x1.8")
	_, _ = parseHexFloat("0x1")
	_, _ = parseInterpolatedString(`"hello $(1)"`, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = parseInterpolatedString(`"hello $(name)"`, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _, _ = unescapeSequence(`\u0041`)
	_, _, _ = unescapeSequence(`\x`)
	_, _ = parseUnicodeEscape(`\u0041`, 4)
	_, _ = parseUnicodeEscape(`\u0`, 4)

	_, _ = evaluateArrayAccess(ast.ArrayAccess{Target: ast.StringLiteral{Lexeme: `"Ada"`}, Index: ast.IntLiteral{Lexeme: "foo"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateInfix(ast.InfixExpression{Operator: lexer.TokenEOF, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "2"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateLogicalAnd(ast.InfixExpression{Left: ast.BooleanLiteral{Value: true}, Right: ast.IntLiteral{Lexeme: "1"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateLogicalOr(ast.InfixExpression{Left: ast.BooleanLiteral{Value: false}, Right: ast.IntLiteral{Lexeme: "1"}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateConditional(ast.ConditionalExpression{Condition: ast.IntLiteral{Lexeme: "1"}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bea"`}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateArrayLiteral(ast.ArrayLiteral{Elements: []ast.Expression{ast.IntLiteral{Lexeme: "1"}}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateRecordLiteral(ast.RecordLiteral{Fields: []ast.RecordField{{Name: "name", Value: ast.StringLiteral{Lexeme: `"Ada"`}}, {Name: "name", Value: ast.StringLiteral{Lexeme: `"Bea"`}}}}, newValueEnvironment(), Value{}, symbols, types, schemas, nil)
	_, _ = evaluateSelfReference(ast.SelfReference{Path: []string{"name"}}, Value{Kind: ValueString, String: "Ada"})

	_, _ = inferExpressionType(ast.MemberAccess{Target: ast.StringLiteral{Lexeme: `"Ada"`}, Name: "name"}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.ArrayAccess{Target: ast.StringLiteral{Lexeme: `"Ada"`}, Index: ast.IntLiteral{Lexeme: "0"}}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.IntLiteral{Lexeme: "1"}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.FloatLiteral{Lexeme: "1.5"}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.HexIntLiteral{Lexeme: "0xA"}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.HexFloatLiteral{Lexeme: "0x1.8"}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.StringLiteral{Lexeme: `"Ada"`}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.BooleanLiteral{Value: true}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.NullLiteral{}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.ArrayLiteral{Elements: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}}}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.RecordLiteral{Fields: []ast.RecordField{{Name: "name", Value: ast.StringLiteral{Lexeme: `"Ada"`}}}}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.SelfReference{Path: []string{"name"}}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.PrefixExpression{Operator: lexer.TokenMinus, Right: ast.IntLiteral{Lexeme: "1"}}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.InfixExpression{Operator: lexer.TokenPlus, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "2"}}, vars, symbols, types, schemas, nil)
	_, _ = inferExpressionType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bea"`}}, vars, symbols, types, schemas, nil)
	var badExprType ast.Expression
	_, _ = inferExpressionType(badExprType, vars, symbols, types, schemas, nil)

	_, _ = inferArrayLiteralType(ast.ArrayLiteral{}, vars, symbols, types, schemas, nil)
	_, _ = inferArrayLiteralType(ast.ArrayLiteral{Elements: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}, ast.StringLiteral{Lexeme: `"Bea"`}}}, vars, symbols, types, schemas, nil)
	_, _ = inferPrefixType(ast.PrefixExpression{Operator: lexer.TokenBang, Right: ast.BooleanLiteral{Value: true}}, vars, symbols, types, schemas, nil)
	_, _ = inferPrefixType(ast.PrefixExpression{Operator: lexer.TokenTilde, Right: ast.IntLiteral{Lexeme: "1"}}, vars, symbols, types, schemas, nil)
	_, _ = inferPrefixType(ast.PrefixExpression{Operator: lexer.TokenMinus, Right: ast.IntLiteral{Lexeme: "1"}}, vars, symbols, types, schemas, nil)
	_, _ = inferPrefixType(ast.PrefixExpression{Operator: lexer.TokenEOF, Right: ast.IntLiteral{Lexeme: "1"}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenPlus, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "2"}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenIn, Left: ast.StringLiteral{Lexeme: `"name"`}, Right: ast.Identifier{Name: "record"}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenMerge, Left: ast.RecordLiteral{}, Right: ast.RecordLiteral{}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenPercent, Left: ast.IntLiteral{Lexeme: "5"}, Right: ast.IntLiteral{Lexeme: "2"}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenShiftLeft, Left: ast.HexIntLiteral{Lexeme: "0x1"}, Right: ast.IntLiteral{Lexeme: "1"}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenAmpersand, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "2"}}, vars, symbols, types, schemas, nil)
	_, _ = inferInfixType(ast.InfixExpression{Operator: lexer.TokenEOF, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "2"}}, vars, symbols, types, schemas, nil)
	_, _ = inferConditionalType(ast.ConditionalExpression{Condition: ast.IntLiteral{Lexeme: "1"}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bea"`}}, vars, symbols, types, schemas, nil)
	_, _ = inferConditionalType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.NullLiteral{}, Else: ast.StringLiteral{Lexeme: `"Ada"`}}, vars, symbols, types, schemas, nil)
	_, _ = inferConditionalType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.NullLiteral{}}, vars, symbols, types, schemas, nil)
	_, _ = inferConditionalType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.IntLiteral{Lexeme: "1"}}, vars, symbols, types, schemas, nil)
	_, _ = inferConditionalType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Ada"`}}, vars, symbols, types, schemas, nil)
	_, _ = inferConditionalType(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: false}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bea"`}}, vars, symbols, types, schemas, nil)

	_ = typesEqual(valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}}}, valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}}})
	_ = typesEqual(valueType{members: []valueType{{kind: ValueString}}}, valueType{members: []valueType{{kind: ValueString}}})
	_ = typesEqual(valueType{kind: ValueArray, element: &valueType{kind: ValueString}}, valueType{kind: ValueArray, element: &valueType{kind: ValueString}})
	_ = typesEqual(valueType{kind: ValueArray}, valueType{kind: ValueArray})
	_ = typesEqual(valueType{kind: ValueRecord, schemaName: "User"}, valueType{kind: ValueRecord, schemaName: "Other"})
	_ = ensureAssignable(valueType{kind: ValueString}, valueType{kind: ValueString})
	_ = ensureAssignable(valueType{kind: ValueString, nullable: true}, valueType{kind: ValueNull})
	_ = ensureAssignable(valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}}}, valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}}})
	_ = ensureAssignable(valueType{members: []valueType{{kind: ValueString}}}, valueType{members: []valueType{{kind: ValueString}}})
	_ = ensureAssignable(valueType{kind: ValueArray, element: &valueType{kind: ValueString}}, valueType{kind: ValueArray, element: &valueType{kind: ValueString}})
	_ = ensureAssignable(valueType{kind: ValueArray}, valueType{kind: ValueArray})
	_ = ensureAssignable(valueType{kind: ValueRecord, schemaName: "User"}, valueType{kind: ValueRecord, schemaName: "Other"})
	_ = ensureAssignable(valueType{kind: ValueUnknown}, valueType{kind: ValueString})
	_ = ensureAssignable(valueType{kind: ValueString}, valueType{kind: ValueUnknown})
}
