package processor

import (
	"github.com/louiss0/mace/internal/lexer"
	"github.com/louiss0/mace/internal/parser/ast"
	. "github.com/onsi/ginkgo/v2"
)

var _ = Describe("Strings", func() {
	It("covers parsing and evaluation branches", func() {
		environment := newValueEnvironment()
		environment.Add("name", Value{Kind: ValueString, String: "Ada"})
		environment.Add("profile", Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}})
		symbols := newSymbolTable()
		symbols.Add("name", symbolKindVariable)
		symbols.Add("profile", symbolKindVariable)
		schemas := newSchemaRegistry()
		schemas.Add("User", ast.RecordType{Fields: []ast.SchemaField{{Name: "name", Type: ast.PrimitiveType{Name: "string"}}, {Name: "opt", Optional: true, Type: ast.PrimitiveType{Name: "int"}}}})
		types := newTypeRegistry()

		value, err := parseHexInt("0xFF")
		tAssert.NoError(err)
		tAssert.Equal(int64(255), value.Int)
		_, err = parseHexInt("nope")
		tAssert.Error(err)
		value, err = parseHexFloat("0x2.8")
		tAssert.NoError(err)
		tAssert.InDelta(2.5, value.Float, 0.000001)
		_, err = parseHexFloat("0x2")
		tAssert.Error(err)
		_, err = parseHexFloat("0x2.x")
		tAssert.Error(err)
		_, err = parseDocString(`"not a block"`)
		tAssert.Error(err)
		value, err = parseDocString(`"""block"""`)
		tAssert.NoError(err)
		tAssert.Equal("block", value.String)
		value, err = parseInterpolatedString(`"$(name)"`, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		tAssert.Equal("Ada", value.String)
		value, err = parseInterpolatedString(`'$(name)'`, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		tAssert.Equal("$(name)", value.String)
		_, err = parseInterpolatedString(`"$(profile)"`, environment, Value{}, symbols, types, schemas, nil)
		tAssert.ErrorContains(err, "interpolation requires a scalar value")
		_, err = decodeStringLexeme(`"$(name)"`, false, nil)
		tAssert.Error(err)
		decoded, err := decodeStringLexeme(`"a\n\t\\b"`, false, nil)
		tAssert.NoError(err)
		tAssert.Contains(decoded, "\n")
		_, _, err = unescapeSequence(`\`)
		tAssert.Error(err)
		decoded, width, err := unescapeSequence(`\\`)
		tAssert.NoError(err)
		tAssert.Equal("\\", decoded)
		tAssert.Equal(2, width)
		decoded, width, err = unescapeSequence(`\u0041`)
		tAssert.NoError(err)
		tAssert.Equal("A", decoded)
		tAssert.Equal(6, width)
		_, _, err = unescapeSequence(`\u00G1`)
		tAssert.Error(err)
		_, err = parseUnicodeEscape(`\uD800`, 4)
		tAssert.Error(err)
		end, text, err := interpolationContent("$(a$(b))", 0)
		tAssert.NoError(err)
		tAssert.Equal(8, end)
		tAssert.Equal("a$(b)", text)
		_, _, err = interpolationContent("$(missing", 0)
		tAssert.Error(err)

		tAssert.Equal("null", valueType{kind: ValueNull}.name())
		tAssert.Equal("array<string>", valueType{kind: ValueArray, element: &valueType{kind: ValueString}}.name())
		tAssert.Equal("record<int>", valueType{kind: ValueRecord, element: &valueType{kind: ValueInt}}.name())
		tAssert.Equal("User", valueType{kind: ValueRecord, schemaName: "User"}.name())
		tAssert.Contains(valueType{members: []valueType{{kind: ValueString}, {kind: ValueInt}}}.name(), "variant[")
		tAssert.Contains(valueType{choiceValues: []Value{{Kind: ValueString, String: "Ada"}}}.name(), "choice[")
		tAssert.Equal("int", valueType{kind: ValueInt, nullable: true}.name())

		stringValue, err := stringifyValue(Value{Kind: ValueString, String: "Ada"})
		tAssert.NoError(err)
		tAssert.Equal("Ada", stringValue)
		_, err = stringifyValue(Value{Kind: ValueRecord})
		tAssert.Error(err)
		tAssert.Equal("0x0.0", formatHexFloat(0))
		tAssert.Equal("0x2.0", formatHexFloat(2))
		tAssert.Equal("-0x2.0", formatHexFloat(-2))
		tAssert.Contains(formatHexFloat(1.5), "0x1.")

		_, err = evaluateMemberAccess(ast.MemberAccess{Target: ast.Identifier{Name: "name"}, Name: "length"}, environment, Value{Kind: ValueRecord}, symbols, types, schemas, nil)
		tAssert.Error(err)
		_, err = evaluateMemberAccess(ast.MemberAccess{Target: ast.Identifier{Name: "missing"}, Name: "length"}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.Error(err)
		_, err = evaluateMemberAccess(ast.MemberAccess{Target: ast.Identifier{Name: "name"}, Name: "missing"}, environment, Value{Kind: ValueRecord, Record: map[string]Value{}}, symbols, types, schemas, nil)
		tAssert.Error(err)
		_, err = evaluatePrefix(ast.PrefixExpression{Operator: lexer.TokenMinus, Right: ast.FloatLiteral{Lexeme: "1.5"}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		_, err = evaluatePrefix(ast.PrefixExpression{Operator: lexer.TokenTilde, Right: ast.BooleanLiteral{Value: true}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.Error(err)
		_, err = evaluatePrefix(ast.PrefixExpression{Operator: lexer.TokenQuestion, Right: ast.BooleanLiteral{Value: true}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.Error(err)
		_, err = evaluateInfix(ast.InfixExpression{Operator: lexer.TokenPercent, Left: ast.IntLiteral{Lexeme: "4"}, Right: ast.IntLiteral{Lexeme: "2"}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		_, err = evaluateInfix(ast.InfixExpression{Operator: lexer.TokenShiftLeft, Left: ast.IntLiteral{Lexeme: "4"}, Right: ast.IntLiteral{Lexeme: "1"}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		_, err = evaluateInfix(ast.InfixExpression{Operator: lexer.TokenAmpersand, Left: ast.IntLiteral{Lexeme: "1"}, Right: ast.IntLiteral{Lexeme: "1"}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		valueResult, err := evaluateInfix(ast.InfixExpression{Operator: lexer.TokenAndAnd, Left: ast.BooleanLiteral{Value: false}, Right: ast.IntLiteral{Lexeme: "1"}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		tAssert.False(valueResult.Boolean)
		_, err = evaluateConditional(ast.ConditionalExpression{Condition: ast.BooleanLiteral{Value: true}, Then: ast.StringLiteral{Lexeme: `"Ada"`}, Else: ast.StringLiteral{Lexeme: `"Bob"`}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		_, err = evaluateArrayLiteral(ast.ArrayLiteral{Elements: []ast.Expression{ast.StringLiteral{Lexeme: `"Ada"`}, ast.NullLiteral{}}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.NoError(err)
		_, err = evaluateRecordLiteral(ast.RecordLiteral{Fields: []ast.RecordField{{Name: "name", Value: ast.StringLiteral{Lexeme: `"Ada"`}}, {Name: "name", Value: ast.StringLiteral{Lexeme: `"Bob"`}}}}, environment, Value{}, symbols, types, schemas, nil)
		tAssert.Error(err)
		_, err = evaluateSelfReference(ast.SelfReference{Path: []string{"name"}}, Value{Kind: ValueRecord, Record: map[string]Value{"name": {Kind: ValueString, String: "Ada"}}})
		tAssert.NoError(err)

		_, err = evaluateComparison(lexer.TokenEqualEqual, Value{Kind: ValueInt, Int: 1}, Value{Kind: ValueInt, Int: 2})
		tAssert.Error(err)
		eq, err := evaluateEquality(lexer.TokenNotEqual, Value{Kind: ValueString, String: "Ada"}, Value{Kind: ValueString, String: "Bob"})
		tAssert.NoError(err)
		tAssert.True(eq.Boolean)
		_, err = valuesEqual(Value{Kind: ValueRecord}, Value{Kind: ValueRecord})
		tAssert.Error(err)
	})

	It("covers string escaping and conditional inference helpers", func() {
		parsedDoc, err := parseDocString(`"""docs"""`)
		tAssert.NoError(err)
		tAssert.Equal("docs", parsedDoc.String)
		_, err = parseDocString(`"""docs`)
		tAssert.Error(err)

		unescaped, length, err := unescapeSequence(`\u0041`)
		tAssert.NoError(err)
		tAssert.Equal("A", unescaped)
		tAssert.Equal(6, length)

		_, _, err = unescapeSequence(`\u00ZZ`)
		tAssert.Error(err)

		runeValue, err := parseUnicodeEscape(`\u0041`, 4)
		tAssert.NoError(err)
		tAssert.Equal('A', runeValue)

		tAssert.Equal("0x1.8", formatHexFloat(1.5))
		tAssert.Equal("0x2.0", formatHexFloat(2))

		result, err := inferConditionalType(ast.ConditionalExpression{
			Condition: ast.BooleanLiteral{Value: true},
			Then:      ast.IntLiteral{Lexeme: "1"},
			Else:      ast.IntLiteral{Lexeme: "2"},
		}, &variableRegistry{}, newSymbolTable(), newTypeRegistry(), newSchemaRegistry(), nil)
		tAssert.NoError(err)
		tAssert.Equal(ValueInt, result.kind)
	})

	It("covers escaped string content helpers", func() {
		content, _, err := stringContent(`"""abc\n"""`)
		tAssert.NoError(err)
		tAssert.Contains(content, "abc")
		_, _, err = stringContent(`"""\x`)
		tAssert.Error(err)
		_, err = decodeStringLexeme(`"hello"`, false, func(s string) (string, error) { return s, nil })
		tAssert.NoError(err)
		_, err = decodeStringLexeme(`"unterminated`, false, func(s string) (string, error) { return s, nil })
		tAssert.Error(err)
	})
})
